import { priceTtc } from "./pricing";
import type { Category, Product } from "./types";

export const sampleCategories: Category[] = [
  { code: "K11", name: "Papier reprographie", image_url: null },
  { code: "K20", name: "Écriture", image_url: null },
  { code: "K30", name: "Mobilier", image_url: null },
  { code: "K40", name: "Informatique", image_url: null },
  { code: "K50", name: "Hygiène", image_url: null },
];

function product(
  partial: Omit<Product, "price_ttc" | "barcodes" | "published"> & {
    price_ttc?: number | null;
    barcodes?: string[];
    published?: boolean;
  },
): Product {
  const vat = partial.vat_rate ?? 0;
  const price_ttc =
    partial.price_ttc !== undefined
      ? partial.price_ttc
      : partial.price_ht == null
        ? null
        : priceTtc(partial.price_ht, vat);
  return {
    ...partial,
    price_ttc,
    barcodes: partial.barcodes ?? [],
    published: partial.published ?? true,
  };
}

export const sampleProducts: Product[] = [
  product({
    codpro: "14661",
    name: "RAME A4 80GR MULTIOFFICE",
    slug: "rame-a4-80gr-multioffice-14661",
    description: "Ramette de papier A4 80 g, multifonction. Référence 14661.",
    category_code: "K11",
    category_name: "Papier reprographie",
    unit: "Ramette",
    price_ht: 6.35,
    vat_rate: 4,
    promo_ht: null,
    promo_start: null,
    promo_end: null,
    weight: null,
    stock: 7561,
    image_url: "/samples/14661.svg",
    show_price: true,
    show_stock: true,
  }),
  product({
    codpro: "14680",
    name: "PAPIER A3 80G",
    slug: "papier-a3-80g-14680",
    description: "Papier reprographie format A3, 80 g.",
    category_code: "K11",
    category_name: "Papier reprographie",
    unit: "Ramette",
    price_ht: 12.4,
    vat_rate: 4,
    promo_ht: null,
    promo_start: null,
    promo_end: null,
    weight: null,
    stock: 420,
    image_url: null,
    show_price: true,
    show_stock: true,
  }),
  product({
    codpro: "14702",
    name: "RAMETTE COULEUR INTENSIVE",
    slug: "ramette-couleur-intensive-14702",
    description: "Ramette de papier couleur, usage bureau.",
    category_code: "K11",
    category_name: "Papier reprographie",
    unit: "Ramette",
    price_ht: 8.9,
    vat_rate: 4,
    promo_ht: null,
    promo_start: null,
    promo_end: null,
    weight: null,
    stock: 210,
    image_url: null,
    show_price: true,
    show_stock: true,
  }),
  product({
    codpro: "21015",
    name: "STYLO BILLE BLEU",
    slug: "stylo-bille-bleu-21015",
    description: "Stylo bille encre bleue.",
    category_code: "K20",
    category_name: "Écriture",
    unit: "Pièce",
    price_ht: 0.45,
    vat_rate: 4,
    promo_ht: null,
    promo_start: null,
    promo_end: null,
    weight: null,
    stock: 1500,
    image_url: null,
    show_price: true,
    show_stock: true,
    barcodes: ["DEMO21015"],
  }),
  product({
    codpro: "21040",
    name: "CAHIER 24X32 96 PAGES",
    slug: "cahier-24x32-96-pages-21040",
    description: "Cahier 24 × 32 cm, 96 pages.",
    category_code: "K20",
    category_name: "Écriture",
    unit: "Pièce",
    price_ht: 2.15,
    vat_rate: 4,
    promo_ht: 1.79,
    promo_start: "2026-01-01",
    promo_end: "2026-12-31",
    weight: null,
    stock: 860,
    image_url: null,
    show_price: true,
    show_stock: true,
  }),
  product({
    codpro: "21088",
    name: "MARQUEUR PERMANENT NOIR",
    slug: "marqueur-permanent-noir-21088",
    description: "Marqueur permanent, pointe moyenne.",
    category_code: "K20",
    category_name: "Écriture",
    unit: "Pièce",
    price_ht: 1.8,
    vat_rate: 4,
    promo_ht: null,
    promo_start: null,
    promo_end: null,
    weight: null,
    stock: 0,
    image_url: null,
    show_price: true,
    show_stock: true,
  }),
  product({
    codpro: "33120",
    name: "ARMOIRE METAL 198CM",
    slug: "armoire-metal-198cm-33120",
    description: "Armoire métallique de bureau. Tarif communiqué sur demande.",
    category_code: "K30",
    category_name: "Mobilier",
    unit: "Pièce",
    price_ht: 189,
    vat_rate: 8.5,
    promo_ht: null,
    promo_start: null,
    promo_end: null,
    weight: null,
    stock: 6,
    image_url: null,
    show_price: false,
    show_stock: true,
  }),
  product({
    codpro: "44201",
    name: "TONER LASER NOIR",
    slug: "toner-laser-noir-44201",
    description: "Toner laser noir.",
    category_code: "K40",
    category_name: "Informatique",
    unit: "Pièce",
    price_ht: 64.5,
    vat_rate: 4,
    promo_ht: null,
    promo_start: null,
    promo_end: null,
    weight: null,
    stock: 18,
    image_url: null,
    show_price: true,
    show_stock: true,
  }),
  product({
    codpro: "55110",
    name: "ESSUIE-MAINS BLANC",
    slug: "essuie-mains-blanc-55110",
    description: "Essuie-mains pliés, usage sanitaire.",
    category_code: "K50",
    category_name: "Hygiène",
    unit: "Colis",
    price_ht: 22.9,
    vat_rate: 4,
    promo_ht: null,
    promo_start: null,
    promo_end: null,
    weight: null,
    stock: 40,
    image_url: null,
    show_price: true,
    show_stock: false,
  }),
  product({
    codpro: "55140",
    name: "SAC POUBELLE 100L",
    slug: "sac-poubelle-100l-55140",
    description: "Sacs poubelle 100 litres.",
    category_code: "K50",
    category_name: "Hygiène",
    unit: "Rouleau",
    price_ht: 15.2,
    vat_rate: 4,
    promo_ht: null,
    promo_start: null,
    promo_end: null,
    weight: null,
    stock: 0,
    image_url: null,
    show_price: true,
    show_stock: false,
  }),
];
